name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Either of these works; include both for safety
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          action: upload
          app_location: "/"        # where package.json lives
          output_location: "out"   # change to "dist" if your build outputs dist/
          app_build_command: "npm ci && npm run build"
- uses: actions/setup-node@v4
  with:
    node-version: 18

- name: Install
  run: npm ci

- name: Build (wire API)
  run: |
    VITE_APIURL=https://cippdh3p2.azurewebsites.net npm run build

- name: Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: upload
    app_location: "/"
    output_location: "out"
    skip_app_build: true
